# Generated by Django 3.2.5 on 2021-08-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0002_auto_20210811_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaqCategory',
            new_name='FaqType',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='category',
            new_name='type',
        ),
    ]
    atomic = False
