# Generated by Django 3.2.5 on 2021-10-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_auto_20210811_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='qr_image',
            field=models.ImageField(upload_to='images/qr/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='images/team/'),
        ),
    ]
