# Generated by Django 3.2.5 on 2021-08-08 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubIssue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_id', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentAccountNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentStatistic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('total_tnbc_spent', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('last_transaction_amount', models.IntegerField()),
                ('last_transaction_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_paid_to_projects', models.IntegerField()),
                ('total_paid_to_core_team', models.IntegerField()),
                ('total_paid_as_bounty', models.IntegerField()),
                ('total_paid_by_government', models.IntegerField()),
                ('circulating_supply', models.IntegerField()),
                ('max_supply', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryStatistic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=64)),
                ('balance', models.IntegerField()),
                ('total_tnbc_spent', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('last_transaction_amount', models.IntegerField()),
                ('last_transaction_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_account_number', models.CharField(max_length=64)),
                ('recipient_account_number', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=255)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('memo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statistics.githubissue')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_account_number', models.CharField(max_length=64)),
                ('recipient_account_number', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=255)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('memo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statistics.githubissue')),
            ],
        ),
    ]
