# Generated by Django 3.2.5 on 2021-08-17 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTracker',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=64, unique=True)),
                ('total_scan', models.IntegerField(default=0)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_account_number', models.CharField(max_length=64)),
                ('recipient_account_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('memo', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('block_id', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('TREASURY', 'Treasury')], max_length=255)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=255)),
                ('confirmation_status', models.CharField(choices=[('WAITING_CONFIRMATION', 'Waiting Confirmation'), ('CONFIRMED', 'Confirmed')], max_length=255)),
                ('transaction_status', models.CharField(choices=[('NEW', 'New'), ('IDENTIFIED', 'Identified'), ('UNIDENTIFIED', 'Unidentified'), ('IS_FEE', 'Is Fee')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statistics.githubissue')),
            ],
        ),
        migrations.RemoveField(
            model_name='treasurytransaction',
            name='github_issue',
        ),
        migrations.DeleteModel(
            name='GovernmentTransaction',
        ),
        migrations.DeleteModel(
            name='TreasuryTransaction',
        ),
    ]
