# Generated by Django 3.2.5 on 2021-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_remove_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
