# Generated by Django 3.2.5 on 2021-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0004_alter_transaction_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
