# Generated by Django 3.2.5 on 2021-08-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_alter_transaction_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantracker',
            name='total_scan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='github_issue',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='github_issue_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('NEW', 'New'), ('TIMESHEET', 'Timesheet'), ('PROJECT', 'Project'), ('BOUNTY', 'Bounty'), ('MISCELLANEOUS', 'Miscellaneous'), ('UNIDENTIFIED', 'Unidentified'), ('IS_FEE', 'Is Fee')], default='NEW', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scantracker',
            name='last_scanned',
            field=models.DateTimeField(),
        ),
    ]
