# Generated by Django 3.2.5 on 2021-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_auto_20210823_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubIssue',
        ),
        migrations.AddField(
            model_name='governmentstatistic',
            name='total_tnbc_incoming',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
