# Generated by Django 3.2.5 on 2021-08-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_auto_20210823_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='total_paid_by_government',
        ),
    ]
