# Generated by Django 3.2.5 on 2021-08-26 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_remove_statistic_total_paid_by_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txs_sent_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 11, 25, 33, 610056, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
