# Generated by Django 3.2.5 on 2021-09-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0010_alter_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentstatistic',
            name='account_number',
            field=models.CharField(default='6e5ea8507e38be7250cde9b8ff1f7c8e39a1460de16b38e6f4d5562ae36b5c1a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='governmentaccountnumber',
            name='account_number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
